spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /api/v1/users/${segment}

        - id: team-service-team
          uri: lb://team-service
          predicates:
            - Path=/api/v1/team/**
          filters:
            - RewritePath=/api/v1/team/(?<segment>.*), /api/v1/team/${segment}

        - id: team-service-member
          uri: lb://team-service
          predicates:
            - Path=/api/v1/member/**
          filters:
            - RewritePath=/api/v1/member/(?<segment>.*), /api/v1/member/${segment}

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**, /api/v1/instruments/**
          filters:
            - RewritePath=/api/v1/reservations/(?<segment>.*), /api/v1/reservations/${segment}
            - RewritePath=/api/v1/instruments/(?<segment>.*), /api/v1/instruments/${segment}


        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/v1/boards/**, /api/v1/reply/**
          filters:
            - RewritePath=/api/v1/boards/(?<segment>.*), /api/v1/boards/${segment}
            - RewritePath=/api/v1/reply/(?<segment>.*), /api/v1/reply/${segment}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**, /api/v1/fcm/**
          filters:
            - RewritePath=/api/v1/notification/(?<segment>.*), /api/v1/notification/${segment}
            - RewritePath=/api/v1/fcm/(?<segment>.*), /api/v1/fcm/${segment}



jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

