spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /api/v1/users/${segment}

        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/api/v1/team/**
          filters:
            - RewritePath=/api/v1/team/(?<segment>.*), /api/v1/team/${segment}

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**
          filters:
            - RewritePath=/api/v1/reservations/(?<segment>.*), /api/v1/reservations/${segment}


        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/v1/boards/**, /api/v1/reply/**
          filters:
            - RewritePath=/api/v1/boards/(?<segment>.*), /api/v1/boards/${segment}
            - RewritePath=/api/v1/reply/(?<segment>.*), /api/v1/reply/${segment}



jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

server:
  port: 8080

